# Don't update the version to 2.1.
# The `circleci` command doesn't support 2.1 at this moment.
version: 2

jobs:
  build:
    docker:
      - image: debian:buster-slim
    steps:
      - run:
          command: |
            apt-get update
            apt-get install -y --no-install-recommends ca-certificates curl git
            apt-get install -y --no-install-recommends gcc g++ dos2unix libcurl4-openssl-dev make
            apt-get install -y --no-install-recommends autoconf automake libtool pkg-config
      - run:
          command: |
            mkdir -p /tmp/aribb24
            curl -sSL https://github.com/masnagam/aribb24/archive/master.tar.gz | tar -zx -C /tmp/aribb24 --strip-components=1
            (cd /tmp/aribb24; ./bootstrap)
            (cd /tmp/aribb24; ./configure --prefix=/usr --without-libpng)
            (cd /tmp/aribb24; make && make install)
            rm -rf /tmp/aribb24
      - checkout
      - run:
          # Parallel compilation causes an gcc internal errors like below:
          #
          #   In file included from tsEnumeration.h:36,
          #          from tsMPEG.h:39,
          #          from tsAbstractDefinedByStandards.h:36,
          #          from tsAbstractSignalization.h:36,
          #          from tsAbstractDescriptor.h:36,
          #          from tsSystemClockDescriptor.h:36,
          #          from tsSystemClockDescriptor.cpp:30:
          #   tsUString.h: In destructor 'ts::UString::~UString()':
          #   tsUString.h:141:21: internal compiler error: Segmentation fault
          #        class TSDUCKDLL UString: public std::u16string
          #                        ^~~~~~~
          #   Please submit a full bug report,
          #   with preprocessed source if appropriate.
          #   See <file:///usr/share/doc/gcc-8/README.Bugs> for instructions.
          #
          # Or:
          #
          #   cc1plus: internal compiler error: Segmentation fault
          #   Please submit a full bug report,
          #   with preprocessed source if appropriate.
          #   See <file:///usr/share/doc/gcc-8/README.Bugs> for instructions.
          command: |
            make test ARIB=1 NODTAPI=1 NOPCSC=1
      - run:
          command: |
            make install SYSPREFIX=/usr ARIB=1 NODTAPI=1 NOPCSC=1
            make install-devel SYSPREFIX=/usr ARIB=1 NODTAPI=1 NOPCSC=1
