name: Linux

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install deps
        run: |
          build/install-prerequisites.sh
          sudo apt-get install -y --no-install-recommends autoconf automake libtool pkg-config
      - name: Install aribb24
        run: |
          mkdir -p /tmp/aribb24
          cd /tmp/aribb24
          curl -fsSL https://github.com/masnagam/aribb24/archive/master.tar.gz \
            | tar -xz --strip-components=1
          ./bootstrap
          ./configure --prefix=/usr/local \
            --disable-shared --with-pic --without-libpng
          make -j $(nproc)
          sudo make install
          rm -rf /tmp/aribb24
      - name: Build
        run: |
          make -j $(nproc) ARIB=1 NOCURL=1 NODTAPI=1 NOPCSC=1
        env:
          PKG_CONFIG_PATH: /usr/local/lib/pkgconfig
      - name: Run tests
        run: |
          make -j $(nproc) test ARIB=1 NOCURL=1 NODTAPI=1 NOPCSC=1
      - name: Install
        run: |
          sudo make install SYSPREFIX=/usr/local \
            ARIB=1 NOCURL=1 NODTAPI=1 NOPCSC=1
          sudo make install-devel SYSPREFIX=/usr/local \
            ARIB=1 NOCURL=1 NODTAPI=1 NOPCSC=1
